### ISSUE TITLE
Improve ProB2-UI Error/Warning Dialog

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#139]
The dialog is a bit difficult to use: the default size is often too small, the location column too narrow.

A few ideas
- use relative shorter file paths or have a file and path column
- use a shorter text for line x, column y to line v, column w
- use colours
![Screenshot 2022-05-12 at 16 35 52](https://user-images.githubusercontent.com/1742246/168233451-b7180d3c-d02b-4d41-bc5a-e6a8b297c9cb.png)

Also, in the dialog below it says ProB reported warnings but the Type column says error.

**Comment by leuschel** [comment]
Above is not the default size but already the expanded dialog.

**Comment by yutak001** [comment]
File path has been shortened to file name at the moment to improve readability. I am currently thinking about a solution to this without adding additional columns (I think it would clutter the table view too much, maybe make adding these columns optional?).

Location messages have been shortened to line:column (with (line:column) explanation in header). A tooltip with jump location and corresponding file will be shown too.

I have to investigate further on the warning issue since it seems to work to some extent:
![InclQueue Error and Warning](https://user-images.githubusercontent.com/19926137/186410971-d28ffd61-13e4-43e7-bf28-64247c8ac8f7.png)

**Comment by yutak001** [comment]
I managed to reproduce or create something similar. It seems the VisB error dialogs have been revised since reporting and errors are identified as such.
![button2 json Error](https://user-images.githubusercontent.com/19926137/187696411-130c2a8e-9ce7-4a11-9928-f3fa27795c14.png)
The first error is something to investigate further: No filename given and location is not clear where it is from.
