### ISSUE TITLE
Calls to non-standard Prolog `integer/1` arithmetic function

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#178]
```text
*     Call to non-standard Prolog built-in arithmetic function: integer/1
*       while compiling object avl_tools
*       in file /Users/pmoura/ProB_src/src/avl_tools.pl at or above line 75
```

```text
*     Call to non-standard Prolog built-in arithmetic function: integer/1
*       while compiling object custom_explicit_sets
*       in file /Users/pmoura/ProB_src/src/custom_explicit_sets.pl between lines 4778-4782
```

```text
*     Call to non-standard Prolog built-in arithmetic function: integer/1
*       while compiling object external_functions
*       in file /Users/pmoura/ProB_src/src/external_functions.pl between lines 516-529
```

```text
*     Call to non-standard Prolog built-in arithmetic function: integer/1
*       while compiling object preferences
*       in file /Users/pmoura/ProB_src/src/preferences.pl between lines 2497-2502
```

```text
*     Call to non-standard Prolog built-in arithmetic function: integer/1
*       while compiling object tools_meta
*       in file /Users/pmoura/ProB_src/src/tools_meta.pl between lines 25-28
```

For better code portability, it likely can be replaced by a call to the standard `truncate/1` function. See:
https://sicstus.sics.se/sicstus/docs/latest4/html/sicstus.html/ref_002dari_002daex.html

**Comment by dgelessus** [comment]
For reference, I already ran into this during the SWI port. Not sure why I didn't fix it everywhere yet - possibly I wasn't able to find the other uses using a simple text search, because `integer` is such a common identifier.

This one is particularly problematic because `integer` also exists in SWI, but with different semantics than SICStus. (SICStus `integer` behaves like `truncate`, SWI `integer` behaves like `round`.)

**Comment by pmoura** [comment]
Those are all I found so far in the `ProB_src/src` directory. I have not yet looked into the sub-directories.

**Comment by leuschel** [comment]
There were more uses of integer/1 I found in alloy2b and kernel_waitflags for example.
I have also replaced uses of integer(2**X+C) by 2^X+C in some cases, avoiding the float usage all together.
(Earlier SICStus did not have the ^ operator.)

**Comment by dgelessus** [comment]
I had to revert some uses of the `^` operator back to `**`, because for some reason the integer `^` operator crashes SICStus on Windows under specific circumstances. (I've reported this to SICStus and it will hopefully be fixed in the next release.) The integer conversion now uses `truncate` or `floor` instead of `integer` though, so Logtalk should still be happy.

**Comment by pmoura** [comment]
Good find! Do you have a reproducible case for that crash?

**Comment by dgelessus** [comment]
The test code I used is:

```prolog
calc(Height, Size) :-
	Size is Height^2 - 1.
crash :-
	calc(13, _),
	crash.
```

Save as crash.pl and run using `sicstus -l crash.pl --goal "crash."`, then press Ctrl+C while it's running. Sometimes, instead of showing the `Prolog interruption` prompt, SICStus will crash. If `^` is replaced with `**`, it never crashes.

For some reason, the crash only happens for me when running Windows inside a VM. (Windows version doesn't seem to matter - happens on both Windows 10 and 11.) So far I couldn't reproduce it with Windows running on real hardware.

**Comment by pmoura** [comment]
Thanks. It look likes a signal handling bug.
