### ISSUE TITLE
Improve portability of files calling the de facto standard `forall/2` predicate

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#202]
In the `alloy2b/alloy2b.pl`, `dpllt_solver/dpllt_sat_solver.pl`, and `synthesis/deep_learning/ground_truth.pl` files, the line:

```logtalk
:- use_module(library(aggregate),[forall/2]).
```
can be replaced with:

```logtalk
:- if(\+ predicate_property(forall(_, _), _)).
	:- use_module(library(aggregate),[forall/2]).
:- endif.
```

This avoids a compilation error with Logtalk and a loading warning with SWI-Prolog.

**Comment by dgelessus** [comment]
Hm, this is a tricky one - not because it's hard to solve, but because it opens the whole can of worms about predicates with inconsistent names/modules between different systems. When I first started experimenting with porting to SWI, I tried solving all of the SICStus/SWI naming differences using conditionals like this. This is possible of course, but it's a lot of manual work, and requires either copy-pasting these conditionals everywhere or writing a small custom compatibility module. That's a big reason why I settled on using the `expects_dialect` mechanism for SWI compatibility, because it takes care of these trivial differences with almost no manual changes.

I'm guessing that in Logtalk on SWI, the `expects_dialect` directive isn't available/usable? Is `forall/2` the only predicate that would require a change like this, or would similar changes also be needed for `library(lists)`, `library(system)`, etc.? It would be unfortunate if native Logtalk support would require handling all of these trivial differences manually after all 🙁

**Comment by dgelessus** [comment]
> This avoids a compilation error with Logtalk

I'm a bit confused about this as well. I understand that Logtalk provides `forall/2` as a builtin regardless of whether the backend implements it as a builtin or a library predicate. But does Logtalk's implicit builtin `forall/2` conflict with importing the same predicate from the SICStus `library(aggregate)`?

**Comment by pmoura** [comment]
Good questions. For most of the common library predicates, Logtalk provides portable libraries (e.g. lists, random, sets, dictionaries, ...) and libraries that  abstract when necessary the differences between systems (e.g. format, coroutining, ...). Thus, at the application level, for these library predicates, no conditional compilation directives or an `expects_dialect` like solution is required.

I have worked-around the `forall/2` clash in the Logtalk `settings.lgt` file by simply suppressing the directive using the term-expansion mechanism (this mechanism is also fully portable and thus could avoid the current trouble caused by the differences between SICStus and SWI).

Indeed the Logtalk `forall/2` built-in predicate causes a conflict with that `use_module/2` directive. In general, as you also hinted, there's no reliable way to check if semantics are the same for these predicates.

I suggest we close this issue. But happy to continue here to discuss/clarify these kind of issues.
