### ISSUE TITLE
ProB2-UI JSON Trace Export for Rodin Packages has wrong model name

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#243]
When saving a trace in ProB2-UI for an Event-B .eventb package file you get errors during replay.

<img width="617" alt="Screenshot 2022-11-18 at 13 44 28" src="https://user-images.githubusercontent.com/1742246/202727025-e09963c9-93f2-45ba-a186-bf15d80376e6.png">

One could of course weaken the check/warning in prob_prolog, but probably the ProB2 export should use the real model name and not the file name.

**Comment by dgelessus** [comment]
To be exact, ProB 2 UI doesn't even use the file name, but rather the name of the machine in the project file. If the project contains multiple machines with the same name, some of them will have a number appended, like the "(2)" in your example. Unfortunately, this makes it impossible to check the model name field correctly outside ProB 2 UI.

I don't know if it helps much to change ProB 2 UI's behavior now, because many existing trace files will still have problematic model names in them. It may be better to add a new separate field with a properly defined meaning, and check the old field less strictly (or not at all).

**Comment by leuschel** [comment]
I have made the check in prob_prolog more lenient in commit ee4ac0ec5402c8f0c66c866440c7550948c47a26
