### ISSUE TITLE
Pro B is not responding

### ISSUE THREAD

**Issue by ganguliSilva** [hhu-stups/prob-issues#264]
The title bar is displaying (not responding ) and the Enabled operations pane is showing Opening...
But nothing is happening even though I kept it for more than 30mins
OS: Windows 11
Pro B version: 1.11.1-final

**Comment by iTitus** [comment]
Is the UI totally unresponsive? Can you try to bringup the "Help -> About ProB2" dialog to check all the versions?

If it is totally unresponsive there might be some kind of user input that's required, are there any dialogs open in the background?

**Comment by leuschel** [comment]
Can you try using the latest nightly build (https://prob.hhu.de/w/index.php?title=Download#Nightly_Builds)?
Can you try putting ProB into verbose mode before loading a B machine by choosing "Debugging Info" in the Debug menu? What happens when you run the command-line version of ProB: ```probcli.exe Sets.mch -init -v```

You can also try "Check Java and Parser Version" in the debug menu. My suspicion, however, is that the Windows firewall is preventing ProB Tcl/Tk to communicate with the Java parser.

**Comment by ganguliSilva** [comment]
Hi,
Appreciate your reply. It was a minor issue and I fixed it.

Thank you.

**Comment by iTitus** [comment]
Please re-open if this is still an issue.
