### ISSUE TITLE
Make Visualisation menu also available for VisB or other windows

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#279]
It would be nice if the Visualisation and possible the Advanced menu would also be available
when the VisB (or other windows like Graph or Table Visualisation) is topmost.
In a lot of cases, this would avoid having to first click on the main window (which on small screens is sometimes hidden behind the VisB window).

**Comment by dgelessus** [comment]
This is a bit specific to macOS, where the menu bar is attached to the top of the screen. On other systems, the menu bar is part of the main window, so you *always* have to click on the main window to access most menus.

On Mac, the main menu bar is always accessible, unless the currently focused window has its own menu bar, like e. g. VisB and the graphvisualization window - in that case, that window's menu takes priority. Possible solutions would be:

* Remove the custom menu bars in the non-main windows.
  * This could be done in the graph visualization window, where the menu only really exists to capture the key combinations for zooming in and out (so that they zoom only the graph view instead of the entire UI).
  * It's not as easy with VisB, because it has more custom menu items. Almost all of them are also accessible from the VisB toolbar, but that's already quite full, so removing the menu bar there may be bad for usability.
* Copy the main menu bar to the non-main windows (and add custom menu items for each window as appropriate). I don't know how well this would work on non-Mac systems - it might be confusing to have multiple copies of (almost) identical menu bars.
* Integrate VisB into the main window, e. g. as a tab next to "State Visualization" (see #299). Then it would automatically have the main menu bar, but we would have to figure out how to integrate the VisB-specific menu items into the main menus...
