### ISSUE TITLE
"Close Window"-option shows no confirmation-option or warning

### ISSUE THREAD

**Issue by Inab1993** [hhu-stups/prob-issues#309]
when clicking the "close window"-button in the file menu, the program shuts down immediately, but throws neither any warnings when unsaved changes are made, nor asks for a confirmation. Maybe the title of the button should be renamed (e.g. "exit") and some confirmations or alerts should be shown. (same applies to the x-button)

**Comment by dgelessus** [comment]
In principle this is already implemented. For example, if you add/remove a machine in a project and then close the window without saving, you get a confirmation dialog asking if you want to save the project. This works both with the close button in the title bar and with the "Close" menu item.

The problem is that currently only project changes are detected, but not e. g. if you have unsaved changes in the editor. Also, some changes to the project don't set the "changed" flag correctly (I don't remember which exactly).
