### ISSUE TITLE
BEditor: Undo/Redo by pressing CRTL(+Shift)+Z fails for Linux

### ISSUE THREAD

**Issue by yutak001** [hhu-stups/prob-issues#36]
Undo/Redo functionality seems to be broken for my Linux. Since I have a german keyboard I tried CRTL(+Shift)+Y too - to no avail.

Undoing and redoing by menu seems to work.

**Comment by yutak001** [comment]
I found a comment on how Keycode.Z is confused with Keycode.Y for German keyboards: At least for my Linux (OpenSuse Tumbleweed) this is not the case. It might be that some other distributions or older linux versions still have this problem. I can not speak for other OS since I have not been using them for years.

**Comment by yutak001** [comment]
I fixed this issue (for me at least) by adding a KeyCode.Z comparison for KeyEvent.getCode. It should work for other OSs too. Reopen if necessary.

**Comment by dgelessus** [comment]
Unfortunately with this change, Cmd+Y on macOS with a German keyboard is recognized as Undo/Cmd+Z. This isn't a big problem, because we don't use Cmd+Y for anything, but it's not very nice.

I experimented a bit, and it seems that JavaFX reports key codes inconsistently on different OSes. On macOS, `KeyEvent.getCode()` always returns the key code based on the US keyboard layout, regardless of what layout the user has set - so for example pressing the "Z" key with a German keyboard layout returns `KeyCode.Y`. On Linux (I tested under Kubuntu 20.04), `KeyEvent.getCode()` returns the key code based on the current keyboard layout - so for example "Z" with a German keyboard layout returns `KeyCode.Z`. I think this is what the comment is talking about.

`KeyEvent.getText()` always returns the key's character based on the current keyboard layout, so for example when pressing "Z" with a German keyboard layout, it returns `"z"` on both Mac and Linux (lowercase because Shift isn't pressed). But there is some strange behavior here too: if the Control key is pressed, `KeyEvent.getText()` returns a control character instead of the normal letter. For example, pressing Control+Z returns `"\u001a"` instead of `"z"`. (U+001A is the control character that you get in a terminal when you press Control+Z.) This happens only for the Control key and not for Command on Mac, so if we check based on `KeyEvent.getText()`, we need to check for two different versions of the text: the normal character and the corresponding control character. Also, this does *not* happen if Shift is pressed - for Shift+Control+Z, `KeyEvent.getText()` returns `"Z"`.

I think the best apporach would be to use `KeyEvent.getText()` for editor shortcuts and not `KeyEvent.getCode()`, so that non-US keyboard layouts are handled correctly. Sadly this means that we have to list most key combinations twice to handle the control characters correctly.

I also haven't tested on Windows yet, so I don't know how JavaFX behaves there.

**Comment by yutak001** [comment]
Thank you for pointing that out :) I tried to deal with those problems (it's not pretty...) and I hope I got a solution (for Mac and Linux at least). Since I lack a macOS could you please try if it's back to normal again? Linux should be working now.

**Comment by dgelessus** [comment]
Thank you, it seems to work correctly now on Mac! There was a small bug on Linux where pressing Z *without* Ctrl also caused an undo/redo, but that should be fixed now (hhu-stups/prob2_ui@93ef1d226440902bafbaad5a0f30906f4b811d02). Once the build has finished I'll test this version on Windows.

**Comment by dgelessus** [comment]
OK, undo/redo is now working correctly on Linux, Mac and Windows. There's a different bug in the editor on Windows where the Shift key doesn't work, but that seems to be unrelated to this issue, so I've opened a separate issue: #54
