### ISSUE TITLE
ProB2-UI 1.1.0 and snapshot seem to share global preferences

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#42]
This means that when we use a new value allowed in 1.1.1, 1.1.0 can no longer be used to open any machine.

We could provide two solutions:
- clearly separate configuration files per version
- ensure that a wrong preference does not prevent loading machines (e.g., by changing set_eclipse_preference in prob2_interface or change the logic in Java)

![Screenshot 2021-02-27 at 12 08 41](https://user-images.githubusercontent.com/1742246/109385883-36686a80-78f7-11eb-9906-114b65519a31.png)

**Comment by leuschel** [comment]
I have already changed set_eclipse_preference in prob2_interface to include the name of the preference in the error message.

**Comment by dgelessus** [comment]
Since hhu-stups/prob2_ui@3a59098f7845672e16be572bf53f97fbeede55d1, the config file is now saved under a new name whenever the config file format changes, which usually happens at least once between UI releases. Global preferences are stored in the config file, so this means that different releases of the UI should now have different global preference settings.

This isn't a perfect solution to this problem, because normally the config version is only bumped when the config format changes (usually when a new config setting is added), and just updating probcli doesn't change the config format. We could work around that by always bumping the config version whenever we update probcli, even if the config format didn't actually change.
