### ISSUE TITLE
Project file does not update on changes

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#57]
When editing a project file in an external editor, and reloading the project in ProB2-UI afterwards, the project file does not update. One has to switch to another project first

**Comment by dgelessus** [comment]
This should be fixed now as part of #58.

The original motivation for this was that the LTL editors were sometimes broken, so the only way to add LTL formulas was by manually editing the project file. This is no longer necessary, because we have now switched to a different editor for LTL (hhu-stups/prob2_ui@dca366e5f00b7eae801718878630ce99677553f7).
