### ISSUE TITLE
Update Strings in ResourceBundles

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#7]
Main Focus: Strings in French, VisB Strings also for German

**Comment by dgelessus** [comment]
The German and French localizations are now complete and up-to-date again.

Russian is still incomplete, because we don't have anyone who speaks the language and could update it. The Portuguese localization was removed (hhu-stups/prob2_ui@e1aaa0b32083063019721ea11fd77d2537084107) because it was very incomplete and we don't have anyone to update it either.
